
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from "../types";

export const swapFacesInPoster = async (
  posterBase64: string, 
  faceBase64s: string[], 
  instructions?: string,
  aspectRatio: AspectRatio = "3:4"
) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const posterPart = {
    inlineData: {
      mimeType: "image/png",
      data: posterBase64.split(',')[1]
    }
  };

  const faceParts = faceBase64s.map((base64) => ({
    inlineData: {
      mimeType: "image/png",
      data: base64.split(',')[1]
    }
  }));

  const prompt = `STRICT ARCHITECTURAL COMMAND: Perform a high-fidelity, hyper-realistic theatrical movie poster RECONSTRUCTION.

REFERENCE ROLE ASSIGNMENTS:
1. TARGET MOVIE POSTER (Image 1): Master for POSE, FACIAL EXPRESSION, GAZE DIRECTION, EYE COLOR, OUTFIT, LIGHTING, ENVIRONMENT, COMPOSITION, TEXTURES, and ALL TEXT.
2. SOURCE IDENTITY REFERENCES (Images 2-${faceParts.length + 1}): Use strictly for LIKENESS, BONE STRUCTURE, and INDIVIDUAL IDENTITY accuracy.

EXPRESSION & POSE MAPPING PROTOCOL:
- RE-GENERATE the faces of the subjects in the Target Poster using the Source Identity References.
- MANDATORY: The new faces must INHERIT the exact facial expression, head tilt, and eye gaze direction of the original characters in the poster.
- OCULAR & COLOR FIDELITY: Replicate any stylized or exaggerated eye colors from the Target Subject.
- ARTISTIC STYLE: Match the original poster's artistic medium, film grain, and lighting perfectly.
- BRANDING PRESERVATION: Keep all original text, titles, and layouts exactly as they appear in Image 1.

${instructions ? `DIRECTOR'S CREATIVE DIRECTION: ${instructions}. Lean the artistic style, color grading, and facial refinement specifically toward this instruction.` : ''}

FORMATTING: The output must adhere to a ${aspectRatio} aspect ratio. If the original poster was a different shape, expand the environment and backgrounds naturally to fill the new cinematic frame while keeping the subjects centered and properly scaled.

STYLE: Photorealistic, Cinematic, VFX-grade. Return ONLY the final image.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          posterPart,
          ...faceParts,
          { text: prompt }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio, 
          imageSize: "1K"
        }
      }
    });

    if (!response.candidates || response.candidates.length === 0) {
      throw new Error("No image generated by the AI.");
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("Result did not contain image data.");
  } catch (error: any) {
    if (error.message?.includes("Requested entity was not found")) {
      throw new Error("API_KEY_ERROR");
    }
    throw error;
  }
};

export const animatePoster = async (posterBase64: string, instructions?: string, aspectRatio: AspectRatio = "9:16") => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Mapping our UI ratios to Veo supported ratios (16:9 or 9:16)
  const veoRatio = aspectRatio === "3:4" ? "9:16" : "9:16";

  const videoPrompt = `A high-end cinematic moving photograph. Bring the human subjects to life with extremely subtle, natural lifelike movements such as gentle breathing, blinking, and slight head shifts. Maintain the high-fidelity likeness of the faces perfectly.
  STRICT VISUAL CONSTRAINT: DO NOT add any artificial lighting elements, lens flares, sparkles, star bursts, star-like shining objects, or glowing particles that blow out the scene. Do not add any white-out flashes or extra shining overlays. 
  Maintain the original poster's lighting, contrast, and color environment exactly as it is without adding new light sources.
  ${instructions ? `MOTION DIRECTION: ${instructions}. Integrate this into the natural cinematic flow without breaking the lighting constraints.` : ''}
  Professional motion poster style. High quality vfx. No distorted face warping or morphing.`;

  try {
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: videoPrompt,
      image: {
        imageBytes: posterBase64.split(',')[1],
        mimeType: 'image/png',
      },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: veoRatio
      }
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
      
      if (operation.error) {
        throw new Error(`Render Error: ${operation.error.message || 'The production was interrupted.'}`);
      }
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) throw new Error("Could not retrieve motion render link.");

    const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    if (!videoResponse.ok) throw new Error("Failed to download cinematic file.");
    
    const videoBlob = await videoResponse.blob();
    return URL.createObjectURL(videoBlob);
  } catch (error: any) {
    if (error.message?.includes("Requested entity was not found")) {
      throw new Error("API_KEY_ERROR");
    }
    throw error;
  }
};
